version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies for testing...
      - cd blacklist-service
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - echo Running unit tests...
      - pytest -v --cov=src --cov-report=term --cov-report=html
      - echo Tests completed successfully
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 127214179230.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t blacklist_app .
      - docker tag blacklist_app:latest 127214179230.dkr.ecr.us-east-1.amazonaws.com/blacklist_app:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 127214179230.dkr.ecr.us-east-1.amazonaws.com/blacklist_app:latest

reports:
  pytest_reports:
    files:
      - 'htmlcov/**/*'
    base-directory: blacklist-service
    
artifacts:
  files:
    - "**/*"
  base-directory: blacklist-service
