version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - cd blacklist-service
      - pip install -r requirements.txt
      - cd ..

  pre_build:
    commands:
      - echo "Running unit tests..."
      - cd blacklist-service
      - pytest -v --cov=src --cov-report=term --cov-report=html
      - cd ..
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 014487871519.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t entrega_3_blacklist blacklist-service
      - docker tag entrega_3_blacklist:latest 014487871519.dkr.ecr.us-east-1.amazonaws.com/entrega_3_blacklist:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push 014487871519.dkr.ecr.us-east-1.amazonaws.com/entrega_3_blacklist:latest
      - echo "Generating artifact files..."
      - IMAGE_URI="014487871519.dkr.ecr.us-east-1.amazonaws.com/entrega_3_blacklist:latest"
      - printf '[{"name":"blacklist_entrega3","imageUri":"%s"}]' "$IMAGE_URI" > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' "$IMAGE_URI" > imageDetail.json
      - echo "Artifacts generated."

reports:
  pytest_reports:
    files:
      - "htmlcov/**/*"
    base-directory: blacklist-service
artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
    - appspec.json
    - taskdef.json
